//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace EstadosdePagos.WsSesion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_SesionSoap", Namespace="http://tempuri.org/")]
    public partial class WS_Sesion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IniciarOperationCompleted;
        
        private System.Threading.SendOrPostCallback TerminarOperationCompleted;
        
        private System.Threading.SendOrPostCallback FechaHoraOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_Sesion() {
            this.Url = global::EstadosdePagos.Properties.Settings.Default.EstadosdePagos_WsSesion_Sesion1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IniciarCompletedEventHandler IniciarCompleted;
        
        /// <remarks/>
        public event TerminarCompletedEventHandler TerminarCompleted;
        
        /// <remarks/>
        public event FechaHoraCompletedEventHandler FechaHoraCompleted;
        
        /// <remarks/>
        public event ObtenerUsuarioCompletedEventHandler ObtenerUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Iniciar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sesion Iniciar(string Usuario, int Maquina, string Terminal, string App) {
            object[] results = this.Invoke("Iniciar", new object[] {
                        Usuario,
                        Maquina,
                        Terminal,
                        App});
            return ((Sesion)(results[0]));
        }
        
        /// <remarks/>
        public void IniciarAsync(string Usuario, int Maquina, string Terminal, string App) {
            this.IniciarAsync(Usuario, Maquina, Terminal, App, null);
        }
        
        /// <remarks/>
        public void IniciarAsync(string Usuario, int Maquina, string Terminal, string App, object userState) {
            if ((this.IniciarOperationCompleted == null)) {
                this.IniciarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIniciarOperationCompleted);
            }
            this.InvokeAsync("Iniciar", new object[] {
                        Usuario,
                        Maquina,
                        Terminal,
                        App}, this.IniciarOperationCompleted, userState);
        }
        
        private void OnIniciarOperationCompleted(object arg) {
            if ((this.IniciarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IniciarCompleted(this, new IniciarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Terminar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sesion Terminar(int idSession) {
            object[] results = this.Invoke("Terminar", new object[] {
                        idSession});
            return ((Sesion)(results[0]));
        }
        
        /// <remarks/>
        public void TerminarAsync(int idSession) {
            this.TerminarAsync(idSession, null);
        }
        
        /// <remarks/>
        public void TerminarAsync(int idSession, object userState) {
            if ((this.TerminarOperationCompleted == null)) {
                this.TerminarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTerminarOperationCompleted);
            }
            this.InvokeAsync("Terminar", new object[] {
                        idSession}, this.TerminarOperationCompleted, userState);
        }
        
        private void OnTerminarOperationCompleted(object arg) {
            if ((this.TerminarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TerminarCompleted(this, new TerminarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FechaHora", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sesion FechaHora() {
            object[] results = this.Invoke("FechaHora", new object[0]);
            return ((Sesion)(results[0]));
        }
        
        /// <remarks/>
        public void FechaHoraAsync() {
            this.FechaHoraAsync(null);
        }
        
        /// <remarks/>
        public void FechaHoraAsync(object userState) {
            if ((this.FechaHoraOperationCompleted == null)) {
                this.FechaHoraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechaHoraOperationCompleted);
            }
            this.InvokeAsync("FechaHora", new object[0], this.FechaHoraOperationCompleted, userState);
        }
        
        private void OnFechaHoraOperationCompleted(object arg) {
            if ((this.FechaHoraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechaHoraCompleted(this, new FechaHoraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaDataSet ObtenerUsuario(string login, string clave) {
            object[] results = this.Invoke("ObtenerUsuario", new object[] {
                        login,
                        clave});
            return ((ListaDataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerUsuarioAsync(string login, string clave) {
            this.ObtenerUsuarioAsync(login, clave, null);
        }
        
        /// <remarks/>
        public void ObtenerUsuarioAsync(string login, string clave, object userState) {
            if ((this.ObtenerUsuarioOperationCompleted == null)) {
                this.ObtenerUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerUsuarioOperationCompleted);
            }
            this.InvokeAsync("ObtenerUsuario", new object[] {
                        login,
                        clave}, this.ObtenerUsuarioOperationCompleted, userState);
        }
        
        private void OnObtenerUsuarioOperationCompleted(object arg) {
            if ((this.ObtenerUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerUsuarioCompleted(this, new ObtenerUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sesion {
        
        private int idField;
        
        private System.DateTime fechaField;
        
        private string mensajeErrorField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <comentarios/>
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaDataSet {
        
        private System.Data.DataSet _dataSetField;
        
        private string _errorField;
        
        private System.Data.DataSet dataSetField;
        
        private string mensajeErrorField;
        
        /// <comentarios/>
        public System.Data.DataSet _dataSet {
            get {
                return this._dataSetField;
            }
            set {
                this._dataSetField = value;
            }
        }
        
        /// <comentarios/>
        public string _error {
            get {
                return this._errorField;
            }
            set {
                this._errorField = value;
            }
        }
        
        /// <comentarios/>
        public System.Data.DataSet DataSet {
            get {
                return this.dataSetField;
            }
            set {
                this.dataSetField = value;
            }
        }
        
        /// <comentarios/>
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void IniciarCompletedEventHandler(object sender, IniciarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IniciarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IniciarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sesion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sesion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void TerminarCompletedEventHandler(object sender, TerminarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TerminarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TerminarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sesion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sesion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void FechaHoraCompletedEventHandler(object sender, FechaHoraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechaHoraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechaHoraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sesion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sesion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerUsuarioCompletedEventHandler(object sender, ObtenerUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaDataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaDataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591